/**
 * `doc_read` — the agent's way into Word, Excel, PowerPoint, PDF and subtitle files.
 *
 * Same contract as the workspace tools next door: never throws, a failure is
 * `ERROR: <what to do about it>`, every parameter arrives as a string and is coerced
 * here.
 *
 * ## The result is shaped by the round budget, not by what is in the file
 *
 * All tool output in a round shares 29998 characters (`engine/stages/handoff/budget.ts`),
 * and going over is *silently truncated* — the payload leaves the composer looking
 * complete. A thesis is several times that budget on its own, so this tool answers with
 * an outline first and only ever returns a slice of the body. That is why `mode` defaults
 * to `outline` rather than to "the document".
 *
 * ⚠️ The projection deliberately carries no inline Markdown. The text the agent reads
 * here is text it will later quote back to locate an edit, and a `**` inserted for
 * emphasis would make that quote fail to match the real characters in the file.
 */

import { readDocument } from '@/shared/documents/client';
import type {
  DocOutlineResult,
  DocProjectionResult,
  DocReadMode,
  DocResult,
} from '@/shared/documents/types';
import { resolveWorkspaceId, bindConversation } from '../workspace/workspace-binding';
import { toolCallRecorder } from '../records';

/** Modes the tool accepts, and what an unrecognised value falls back to. */
const MODES: readonly DocReadMode[] = ['outline', 'range', 'search', 'raw'];

function fail(e: unknown): string {
  return `ERROR: ${(e as Error)?.message ?? String(e)}`;
}

function num(value: string | undefined): number | undefined {
  if (value == null || value === '') return undefined;
  const n = Number(value);
  return Number.isFinite(n) ? n : undefined;
}

/**
 * Parse a boolean the model wrote as text.
 *
 * `"true"`, `"True"`, `"1"` and `"yes"` all mean true — the same coercion
 * `workspace-tools.ts` needs, and for the same reason: treating only the exact string
 * `"true"` as true makes a parameter look like it is being ignored.
 */
function bool(value: string | undefined, fallback: boolean): boolean {
  if (value == null || value.trim() === '') return fallback;
  return /^(true|1|yes|on)$/i.test(value.trim());
}

export async function readDocumentTool(
  params: Record<string, string>,
): Promise<string> {
  const path = params.path?.trim();
  if (!path) return 'ERROR: doc_read requires a "path" parameter.';

  const requested = params.mode?.trim().toLowerCase() as DocReadMode | undefined;
  // An unknown mode falls back to `outline` rather than failing: outline is cheap, always
  // valid, and tells the agent enough to ask a better question. Refusing would cost a
  // whole round to correct a typo.
  const mode: DocReadMode =
    requested && MODES.includes(requested) ? requested : 'outline';

  try {
    const workspaceId = await resolveWorkspaceId(
      toolCallRecorder.currentConversationId,
    );

    const result = await readDocument(workspaceId, {
      path,
      mode,
      range: params.range?.trim() || undefined,
      query: params.query?.trim() || undefined,
      formatting: bool(params.formatting, true),
      maxChars: num(params.max_chars),
    });

    // Only after a call actually succeeded: the first successful document operation locks
    // the conversation to this workspace, exactly as the file tools do, so a later call in
    // the same task cannot land somewhere else.
    await lockIn(workspaceId);

    return render(result);
  } catch (e) {
    return fail(e);
  }
}

async function lockIn(workspaceId: string): Promise<void> {
  const sessionId = toolCallRecorder.currentSessionId;
  if (!sessionId) return; // a direct UI call, with nothing to attribute it to
  await bindConversation(
    sessionId,
    toolCallRecorder.currentConversationId,
    workspaceId,
  );
}

// ─── Rendering ───────────────────────────────────────────────────────────────

function render(result: DocResult): string {
  if (result.kind === 'outline') return renderOutline(result);
  if (result.kind === 'projection') return renderProjection(result);
  // `doc_read` cannot produce an edit result; this only exists so the union is closed.
  return JSON.stringify(result);
}

/**
 * The outline, as the agent's first look at a document.
 *
 * Warnings come *before* the outline, not after. They are the things that change what the
 * agent should do next — a document that already carries someone else's tracked changes,
 * text that is generated by a field code — and a warning read after the content is a
 * warning read too late.
 */
function renderOutline(result: DocOutlineResult): string {
  const lines: string[] = [result.summary];

  if (result.facts.length > 0) {
    lines.push(result.facts.join(' · '));
    }

  for (const warning of result.warnings) {
    lines.push(`⚠️ ${warning}`);
  }

  if (result.sections.length === 0) {
    lines.push('No headings or sections were found.');
  } else {
    lines.push('', 'Outline (use the id as doc_read range):');
    for (const section of result.sections) {
      const indent = '  '.repeat(Math.max(0, section.level - 1));
      const size = section.size != null ? `  (${section.size} chars)` : '';
      lines.push(`${section.id}\t${indent}${section.label}${size}`);
    }
  }

  return lines.join('\n');
}

function renderProjection(result: DocProjectionResult): string {
  const header = `${result.path} — ${result.covered}`;
  const body = result.text === '' ? '(no text in this range)' : result.text;

  if (!result.truncated) return `${header}\n${body}`;

  // Say what is missing and how to get it, and rule out the retry the model is most
  // likely to reach for — the same reasoning as `budget.ts`'s `buildNotice()`. Re-running
  // the identical call would truncate in the identical place and burn a round.
  const next = result.nextRange
    ? `Continue with doc_read path="${result.path}" mode="range" range="${result.nextRange}".`
    : 'Narrow the range to see more.';
  return `${header}\n${body}\n\n[Output stops here — this is not the end of the document. ${next}]`;
}
